apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
  labels:
    app: heh-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
          image: omar7000/heh-flask:d31c95fe0be8a50dd78dad78d8d03bb27b7322e3
          imagePullPolicy: IfNotPresent


