apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
  labels:
    app: heh-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
        image: omar7000/heh-flask:8d6344dbfec220357edbcf08fb8365e781171bc3
          imagePullPolicy: IfNotPresent


